name: Build and deploy site and PDF

on:
  push:
    branches:
      - develop

jobs:
  Site-and-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Site
        run: docker-compose run --rm foliant make site --config=foliant.all.yml

      - name: PDF Russian
        run: docker-compose run --rm foliant make pdf --config=foliant.ru.yml

      - name: PDF English
        run: docker-compose run --rm foliant make pdf --config=foliant.en.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: |
            *.pdf

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./constantine-molchanov-cv.mkdocs

